name: Generate Pacman Graph

on:
  schedule:
    - cron: "0 1 * * *"  # Roda diariamente às 01:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate pacman graph
        uses: Platane/pacman@main
        with:
          github_user_name: MaauLobo
          svg_out_path: "dist/pacman-contribution-graph.svg"

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
